<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <meta http-equiv="X-UA-Compatible" content="IE=edge">
    <meta name="viewport" content="width=device-width, initial-scale=1.0">
    <link rel="stylesheet" href="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/css/bootstrap.min.css">
    <link rel="stylesheet" href="https://pro.fontawesome.com/releases/v5.10.0/css/all.css" integrity="sha384-AYmEC3Yw5cVb3ZcuHtOA93w35dYTsvhLPVnYs9eStHfGJvOvKxVfELGroGkvsg+p" crossorigin="anonymous"/>
    <link rel="stylesheet" href="style.css">
    <meta charset="utf-8">
    <link rel="stylesheet" type="text/css" href="style.css" />
    <title>accueil</title>
</head>
<body>
    <h1> Liste des produits </h1>
    <form action="accueil.php" method="post">
      <table class="table table-hover">
          <thead>
            <tr>
              <th scope="col">#</th>
              <th scope="col">Produit</th>
              <th scope="col">Prix</th>
              <th scope="col"></th>
            </tr>
          </thead>
          <tbody>
          <?php foreach($rows as $row): ?>
            <tr>
              <td><?= $row['id']; ?></td>
              <td><?= $row['nom_produit']; ?></td>
              <td><?= $row['prix']; ?></td>
              <td><a href="edit.php?id=<?= $row['id'] ?>"><i class="fas fa-edit"></i></a> <a href="delete.php?id=<?= $row['id'] ?>"><i class="fas fa-trash-alt"></i></a></td>
            </tr>
          <?php endforeach; ?>
            <!-- <tr>
              <th scope="row">3</th>
              <td colspan="2">Larry the Bird</td>
              <td><a href="#"><i class="fas fa-edit"></i></a> <a href="#"><i class="fas fa-trash-alt"></i></a></td>
            </tr> -->
          </tbody>
      </table>
      <a href="connexion.html">Retour</a>
    </form>
</body>
</html>